# Generated by Django 4.0.4 on 2022-05-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.PositiveSmallIntegerField()),
                ('genre', models.CharField(choices=[('Acc', 'Acción'), ('CicFic', 'Ciencia ficción'), ('Com', 'Comedia'), ('Dram', 'Drama'), ('Fan', 'Fantasía'), ('MelDram', 'Melodrama'), ('Mus', 'Musical'), ('Rom', 'Romance'), ('Susp', 'Suspenso'), ('Terr', 'Terror'), ('Doc', 'Documental')], max_length=50)),
                ('director', models.CharField(max_length=150)),
                ('staff', models.JSONField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
